[package]
name = "age-xwing"
version = "0.1.0"
edition = "2024"

[dependencies]
age = "0.11.2"
age-core = "0.11.0"
base64 = "0.22.1"
bech32 = "0.11.1"
hpke-rs = "0.5.0"
hpke-rs-libcrux = "0.5.0"
libcrux-ml-kem = "0.0.4"
rand = "0.9.2"
secrecy = "0.10.3"
sha3 = "0.10.8"
x25519-dalek = "2.0.1"
